DirectSaleNet/DirectSaleNet/Controllers/ManufactorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DirectSaleNet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using DirectSaleNet.Authorize;
namespace DirectSaleNet.Controller
{
    public class ManufactorController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly DirectSaleContext _context;
        public ManufactorController(DirectSaleContext context)
        {
            _context = context;
        }
        //public override void OnActionExecuted(ActionExecutedContext context)
       // {
          //  if(context.HttpContext.Session.GetString("UserID")==null)
            //    context.Result = new RedirectResult("../UserLogin/Login");
         //   else
             //   return;
            //base.OnActionExecuted(context);
        //}
        [Permission("厂商列表",PermissionID ="0102",PermissionName ="厂商查询")]
        [ServiceFilter(typeof(LoginActionFilter))]
        public async Task<IActionResult> ManufactorList(string Province,string Status,string ManufactorName,int? PageIndex,int? id)
        {
            if(id!=null)
            {
                var manu = _context.Manufactor.Find(id);
                if(manu!=null)
                {
                    _context.Manufactor.Remove(manu);
                    _context.SaveChanges();
                }
               
            }
            var manufactor = from m in _context.Manufactor select m;
            if (!string.IsNullOrEmpty(Province))
                manufactor = manufactor.Where(m => m.Province == Province);
            if (!string.IsNullOrEmpty(Status))
                manufactor = manufactor.Where(m => m.Status == Status);
            if (!string.IsNullOrEmpty(ManufactorName))
                manufactor = manufactor.Where(m => m.CompanyName.Contains(ManufactorName));
            ManufactorMode mode = new ManufactorMode();
            int count =await manufactor.CountAsync();
            mode.PageCount = (int)Math.Ceiling(count / (double)mode.PageSize);
            int pageIndex = PageIndex ?? 1;
            mode.PageIndex = (pageIndex >= mode.PageCount ? mode.PageCount : pageIndex);
            //await 异步调用
            mode.manufactors = await manufactor.Skip((pageIndex - 1)*mode.PageSize).Take(mode.PageSize).ToListAsync();
            // _context.Manufactor.FromSql($"select * from Manufactor where province={ProvinceName} and Status={Status} and CompanyName like'%{ManufactorName}%'").ToList();
            var citys = from c in _context.Citys select new { Province = c.Province };
            mode.Provinces = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(citys.Distinct().ToList(), "Province", "Province");
            return View(mode);
        }
        [Permission("厂商注册",PermissionID ="0101",PermissionName = "厂商注册",IsFilter =false)]
        [ServiceFilter(typeof(LoginActionFilter))]
        public ActionResult ManufactorEdit(int? id)
        {
            if(id==null)
            {
                ViewData["Title"] = "厂商注册";
                return View();
            }
            else
            {
                ViewData["Title"] = "编辑厂商信息";
                return View(_context.Manufactor.Find(id));
            }
        }
        [HttpPost]//也就是说点保存的时候调用的，（下面的）  
        public ActionResult ManufactorEdit(int? id,IFormCollection form)
        {
            if(ModelState.IsValid)
            {
                if (id == null)
                {
                    Manufactor manufactor = new Manufactor();
                    manufactor.CompanyName = form["CompanyName"];
                    manufactor.Address = form["Address"];
                    manufactor.Province = form["Province"];
                    manufactor.City = form["City"];
                    manufactor.ContactTel = form["ContactTel"];
                    //manufactor.RegistDate = Convert.ToDateTime(form["RegistDate"]);
                    manufactor.RegistDate = DateTime.Parse(form["RegistDate"]);
                    manufactor.Status = form["Status"];
                    _context.Manufactor.Add(manufactor);
                    _context.SaveChanges();
                }
                else
                {
                    Manufactor manufactor = _context.Manufactor.Find(id);
                    manufactor.CompanyName = form["CompanyName"];
                    manufactor.Address = form["Address"];
                    manufactor.Province = form["Province"];
                    manufactor.City = form["City"];
                    manufactor.ContactTel = form["ContactTel"];
                    //manufactor.RegistDate = Convert.ToDateTime(form["RegistDate"]);
                    manufactor.RegistDate = DateTime.Parse(form["RegistDate"]);
                    manufactor.Status = form["Status"];

                    _context.SaveChanges();
                }
                return RedirectToAction("ManufactorList");
            }
            else
            {
                ModelState.AddModelError("", "数据输入错误，请检查");
                return View();
            }
            
        }
    }
}

DirectSaleNet/DirectSaleNet/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DirectSaleNet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DirectSaleNet.Controller
{
    public class ProductController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly Models.DirectSaleContext _context;
        public ProductController(Models.DirectSaleContext context)
        {
            _context = context;
        }
        // GET: Product
        public ActionResult Index() //获取所有商品
        {
            return View(_context.Product.ToList());
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)  //根据主键 获取明细信息
        {
            return View(_context.Product.Find(id));
        }

        // GET: Product/Create    
        //默认是 GET
        public ActionResult Create() //添加一个商品  insert
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                Product product = new Product();
                product.ProductName = collection["ProductName"];
                product.Brand = collection["Brand"];
                product.Price = decimal.Parse(collection["Price"]);
                product.StockQuantity = int.Parse(collection["StockQuantity"]);
                product.Spec = collection["Spec"];
                product.ManufactorId = int.Parse(collection["ManufactorId"]);
                product.Description = collection["Description"];
                _context.Product.Add(product);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            //Product product = _context.Product.Find(id);
            //Product product = _context.Product.FirstOrDefault(m => m.ProductId == id);

            //return View(product);

            return View(_context.Product.Find(id));
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                Product product = _context.Product.Find(id);
                product.ProductName = collection["ProductName"];
                product.Brand = collection["Brand"];
                product.Price = decimal.Parse(collection["Price"]);
                product.StockQuantity = int.Parse(collection["StockQuantity"]);
                product.Spec = collection["Spec"];
                product.ManufactorId = int.Parse(collection["ManufactorId"]);
                product.Description = collection["Description"];
                _context.SaveChanges();
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_context.Product.Find(id));
        }

        // POST: Product/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Product product = _context.Product.Find(id);
                if (product != null)
                {
                    _context.Product.Remove(product);
                    _context.SaveChanges();
                }
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DirectSaleNet/DirectSaleNet/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using DirectSaleNet.Models;
using DirectSaleNet.Authorize;
using Microsoft.EntityFrameworkCore;
//控制器寻找视图是从同名的文件夹内寻找的，如果没有，就到shared中找
namespace DirectSaleNet.Controller
{
    public class UserLoginController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly DirectSaleContext _context;
        private readonly IHttpContextAccessor httpContext;
        public UserLoginController(DirectSaleContext context,IHttpContextAccessor httpContext)
        {
            _context = context;
            this.httpContext = httpContext;
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]//当点击按钮的时候调用下面的Login
        public ActionResult Login(IFormCollection form)
        {
            //查询表达式，当调用firstorDefault方法是才是调用了数据库
            var user = (from u in _context.User where (u.UserId == form["UserID"] && u.Pwd == form["Pwd"]) select u).FirstOrDefault();
            if(user==null)
            {
                ModelState.AddModelError("", "用户名或密码错误");
                return View();
            }
            else
            {
                //登录当前浏览页面，Session(缓存的)会话保存登录信息，通过Session.setString保存user.UserId，保存到UserID这个参数名中
                httpContext.HttpContext.Session.SetString("UserID", user.UserId);//只保存了编号

                LoginUser loginUser = new LoginUser();
                loginUser.user = user;
                //loginUser.Permissions = _context.Permissions.FromSql($"select * from permissions where permissionid in(select permissionid from authorationuser where userid={user.UserId}) or permissionid in(select permissionid from authorationrole a,userrole u where a.roleid=u.roleid and u.userid={user.UserId})  ").ToList();//查询权限
                loginUser.Permissions = _context.Permissions.FromSql($"execute GetPermission {user.UserId} ").ToList();
                httpContext.HttpContext.Session.Set("LoginUser", Serize<LoginUser>.ObjectToByte(loginUser));//保存了完整信息

                return RedirectToAction("/UserMain");
            }
        }
        public ActionResult UserMain()
        {
            ViewData["Title"] = "用户主页";
            return View();
        }
    }
}

DirectSaleNet/DirectSaleNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DirectSaleNet</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/css/Style1.css" /> <!--~表示根目录-->
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DirectSaleNet</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Product" asp-action="Index">商品列表</a></li>//增加导航
                    <li><a asp-area="" asp-controller="Manufactor" asp-action="ManufactorList">厂家信息</a></li>
                    <li><a asp-area="" asp-controller="UserLogin" asp-action="Login">登录</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()<!--不同的部分-->
        <hr />
        <footer>
            <p>&copy; 2019 - DirectSaleNet</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>